######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 30 18:06:31 2016
######################################################################

QT += webkit
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFI = qt static

# Input
SOURCES += browser.cpp
